# Generated by Django 4.2.2 on 2023-06-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание')),
                ('phone', models.TextField(max_length=30, verbose_name='Номер телефона')),
                ('email', models.TextField(max_length=30, verbose_name='эмайл')),
                ('option', models.TextField(max_length=30, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Субкатегория')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.categories')),
            ],
            options={
                'verbose_name': 'Субкатегория',
                'verbose_name_plural': 'Субкатегории',
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('telephone', models.TextField(default=' ', max_length=30, verbose_name='Номер телефона')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product-images/', verbose_name='Картинка')),
                ('view_count', models.PositiveBigIntegerField(default=0, verbose_name='Количество просмотров')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('type', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='films.categories', verbose_name='Категория')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.subcategories', verbose_name='Субкатегория')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
