# Generated by Django 4.2.2 on 2023-06-21 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_delete_announcements_remove_films_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.categories'),
        ),
    ]
