# Generated by Django 4.2.2 on 2023-09-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_remove_films_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product-images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
