# Generated by Django 4.2.2 on 2023-06-21 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_films_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='email',
            field=models.TextField(default=' ', max_length=100, verbose_name='Емайл телефона'),
        ),
        migrations.AlterField(
            model_name='films',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.categories'),
        ),
        migrations.AlterField(
            model_name='films',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.subcategories'),
        ),
    ]
