# Generated by Django 4.2.2 on 2023-06-22 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_films_email_alter_films_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='films',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='films.categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='films',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='films.subcategories'),
            preserve_default=False,
        ),
    ]
