# Generated by Django 4.2.2 on 2023-09-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_films_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='image',
        ),
    ]
