# Generated by Django 4.2.2 on 2023-06-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_films_type_alter_films_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='email',
            field=models.TextField(max_length=100, verbose_name='Емайл адресс'),
        ),
        migrations.AlterField(
            model_name='films',
            name='telephone',
            field=models.TextField(max_length=30, verbose_name='Номер телефона'),
        ),
    ]
