# Generated by Django 4.2.2 on 2023-06-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_films_email_alter_films_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='author',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
