# Generated by Django 4.2.2 on 2023-09-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_remove_films_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='image',
            field=models.ImageField(blank=True, default='product-images/image.png', null=True, upload_to='product-images/'),
        ),
    ]
