# Generated by Django 4.2.2 on 2023-09-22 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_films_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='telegram',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Телеграмм номер'),
            preserve_default=False,
        ),
    ]
