# Generated by Django 4.2.2 on 2023-09-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_films_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
    ]
