# Generated by Django 4.2.2 on 2023-09-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_country_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag',
        ),
    ]
