# Generated by Django 4.2.2 on 2023-09-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_remove_country_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='in_favorites',
            field=models.BooleanField(default=False),
        ),
    ]
