# Generated by Django 4.2.2 on 2023-09-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_films_in_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='in_favorites',
        ),
    ]
