# Generated by Django 4.2.2 on 2023-06-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_alter_films_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='author',
        ),
    ]
