# Generated by Django 4.2.2 on 2023-09-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_remove_films_in_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='description',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Описание'),
        ),
    ]
