# Generated by Django 4.2.2 on 2023-06-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_films_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='type',
            new_name='film_type',
        ),
    ]
