# Generated by Django 4.2.2 on 2023-06-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_rename_type_films_film_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='film_type',
            new_name='type',
        ),
    ]
