# Generated by Django 4.2.2 on 2023-06-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_rename_film_type_films_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='type',
            new_name='film_type',
        ),
    ]
