# Generated by Django 4.2.2 on 2023-10-10 10:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0015_alter_favorite_user_alter_films_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='User_favorite',
        ),
    ]
