# Generated by Django 4.2.2 on 2023-10-10 12:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0017_rename_user_favorite_userfavorite_delete_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFavorite',
            new_name='Favorite',
        ),
    ]
