# Generated by Django 4.2.2 on 2023-07-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_country_city_films_city_films_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Город'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страна'},
        ),
        migrations.AlterField(
            model_name='city',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.country'),
        ),
        migrations.AlterField(
            model_name='films',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.categories'),
        ),
        migrations.AlterField(
            model_name='films',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.subcategories'),
        ),
    ]
