# Generated by Django 4.2.2 on 2023-10-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_rename_userfavorite_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='is_top_film',
            field=models.BooleanField(default=False),
        ),
    ]
