# Generated by Django 4.2.2 on 2023-10-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0019_films_is_top_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='top_duration',
            field=models.PositiveIntegerField(default=7, verbose_name='Продолжительность в топе (в днях)'),
        ),
    ]
