# Generated by Django 4.2.2 on 2023-07-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0019_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.city'),
        ),
        migrations.AlterField(
            model_name='films',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.country'),
        ),
    ]
