# Generated by Django 4.2.2 on 2023-10-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0020_films_top_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='top_duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Продолжительность в топе (в днях)'),
        ),
    ]
