# Generated by Django 4.2.2 on 2023-07-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0020_alter_films_city_alter_films_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='category',
            new_name='country',
        ),
    ]
