# Generated by Django 4.2.2 on 2023-10-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0022_films_telephone_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='create_date_changed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
