# Generated by Django 4.2.2 on 2023-10-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0023_films_create_date_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='is_price_negotiable',
            field=models.BooleanField(default=False, verbose_name='Договорная цена'),
        ),
    ]
