# Generated by Django 4.2.2 on 2023-10-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_films_is_price_negotiable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
