# Generated by Django 4.2.2 on 2023-10-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0026_alter_films_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_linked',
            field=models.BooleanField(default=False),
        ),
    ]
