# Generated by Django 4.2.7 on 2024-02-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0028_rename_films_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="sub_category",
        ),
        migrations.AddField(
            model_name="products",
            name="sub_category",
            field=models.ManyToManyField(blank=True, to="films.subcategories"),
        ),
    ]
