# Generated by Django 4.2.7 on 2024-02-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0029_remove_products_sub_category_products_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="sub_category",
            field=models.ManyToManyField(
                blank=True, null=True, to="films.subcategories"
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="films.tag"),
        ),
    ]
