# Generated by Django 4.2.2 on 2023-07-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
