# Generated by Django 4.2.2 on 2023-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
