# Generated by Django 4.2.2 on 2023-07-19 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
