# Generated by Django 4.2.2 on 2023-07-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trust',
            field=models.BooleanField(default=False),
        ),
    ]
