# Generated by Django 4.2.2 on 2023-10-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_score_user_banner_user_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_business_account',
            field=models.BooleanField(default=False),
        ),
    ]
